/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.css.cssext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CssExtDslRuntimeModule extends at.bestsolution.efxclipse.tooling.css.cssext.AbstractCssExtDslRuntimeModule {

}
