/*
* generated by Xtext
*/

package at.bestsolution.efxclipse.tooling.css.cssext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class CssExtDslGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class CssExtensionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CssExtension");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cImportsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cImportsImportParserRuleCall_0_0 = (RuleCall)cImportsAssignment_0.eContents().get(0);
		private final Assignment cPackageDefAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cPackageDefPackageDefinitionParserRuleCall_1_0 = (RuleCall)cPackageDefAssignment_1.eContents().get(0);
		
		////	packageDef=PackageDefinition?
		// //	rule=CSSRuleSet
		// CssExtension:
		//
		//	imports+=Import* packageDef=PackageDefinition?;
		public ParserRule getRule() { return rule; }

		//imports+=Import* packageDef=PackageDefinition?
		public Group getGroup() { return cGroup; }

		//imports+=Import*
		public Assignment getImportsAssignment_0() { return cImportsAssignment_0; }

		//Import
		public RuleCall getImportsImportParserRuleCall_0_0() { return cImportsImportParserRuleCall_0_0; }

		//packageDef=PackageDefinition?
		public Assignment getPackageDefAssignment_1() { return cPackageDefAssignment_1; }

		//PackageDefinition
		public RuleCall getPackageDefPackageDefinitionParserRuleCall_1_0() { return cPackageDefPackageDefinitionParserRuleCall_1_0; }
	}

	public class ImportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Import");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cImportedNamespaceAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cImportedNamespaceQualifiedNameWithWildCardParserRuleCall_1_0 = (RuleCall)cImportedNamespaceAssignment_1.eContents().get(0);
		
		//Import:
		//
		//	"import" importedNamespace=QualifiedNameWithWildCard;
		public ParserRule getRule() { return rule; }

		//"import" importedNamespace=QualifiedNameWithWildCard
		public Group getGroup() { return cGroup; }

		//"import"
		public Keyword getImportKeyword_0() { return cImportKeyword_0; }

		//importedNamespace=QualifiedNameWithWildCard
		public Assignment getImportedNamespaceAssignment_1() { return cImportedNamespaceAssignment_1; }

		//QualifiedNameWithWildCard
		public RuleCall getImportedNamespaceQualifiedNameWithWildCardParserRuleCall_1_0() { return cImportedNamespaceQualifiedNameWithWildCardParserRuleCall_1_0; }
	}

	public class ValidIDElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ValidID");
		private final RuleCall cIDTerminalRuleCall = (RuleCall)rule.eContents().get(1);
		
		//ValidID:
		//
		//	ID;
		public ParserRule getRule() { return rule; }

		//ID
		public RuleCall getIDTerminalRuleCall() { return cIDTerminalRuleCall; }
	}

	public class QualifiedNameElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedName");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cValidIDParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final RuleCall cValidIDParserRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		
		//QualifiedName:
		//
		//	ValidID ("." ValidID)*;
		public ParserRule getRule() { return rule; }

		//ValidID ("." ValidID)*
		public Group getGroup() { return cGroup; }

		//ValidID
		public RuleCall getValidIDParserRuleCall_0() { return cValidIDParserRuleCall_0; }

		//(=> "." ValidID)*
		public Group getGroup_1() { return cGroup_1; }

		//=> "."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//ValidID
		public RuleCall getValidIDParserRuleCall_1_1() { return cValidIDParserRuleCall_1_1; }
	}

	public class QualifiedNameWithWildCardElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "QualifiedNameWithWildCard");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cQualifiedNameParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Keyword cFullStopKeyword_1_0 = (Keyword)cGroup_1.eContents().get(0);
		private final Keyword cAsteriskKeyword_1_1 = (Keyword)cGroup_1.eContents().get(1);
		
		//QualifiedNameWithWildCard:
		//
		//	QualifiedName ("." "*")?;
		public ParserRule getRule() { return rule; }

		//QualifiedName ("." "*")?
		public Group getGroup() { return cGroup; }

		//QualifiedName
		public RuleCall getQualifiedNameParserRuleCall_0() { return cQualifiedNameParserRuleCall_0; }

		//("." "*")?
		public Group getGroup_1() { return cGroup_1; }

		//"."
		public Keyword getFullStopKeyword_1_0() { return cFullStopKeyword_1_0; }

		//"*"
		public Keyword getAsteriskKeyword_1_1() { return cAsteriskKeyword_1_1; }
	}

	public class PackageDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PackageDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPackageKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cRulesAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cRulesCSSRuleDefinitionParserRuleCall_3_0_0 = (RuleCall)cRulesAssignment_3_0.eContents().get(0);
		private final Assignment cSubpackagesAssignment_3_1 = (Assignment)cAlternatives_3.eContents().get(1);
		private final RuleCall cSubpackagesPackageDefinitionParserRuleCall_3_1_0 = (RuleCall)cSubpackagesAssignment_3_1.eContents().get(0);
		private final Assignment cElementsAssignment_3_2 = (Assignment)cAlternatives_3.eContents().get(2);
		private final RuleCall cElementsElementDeclartionParserRuleCall_3_2_0 = (RuleCall)cElementsAssignment_3_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//PackageDefinition:
		//
		//	"package" name=QualifiedName "{" (rules+=CSSRuleDefinition | subpackages+=PackageDefinition |
		//
		//	elements+=ElementDeclartion)* "}";
		public ParserRule getRule() { return rule; }

		//"package" name=QualifiedName "{" (rules+=CSSRuleDefinition | subpackages+=PackageDefinition |
		//
		//elements+=ElementDeclartion)* "}"
		public Group getGroup() { return cGroup; }

		//"package"
		public Keyword getPackageKeyword_0() { return cPackageKeyword_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//(rules+=CSSRuleDefinition | subpackages+=PackageDefinition | elements+=ElementDeclartion)*
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//rules+=CSSRuleDefinition
		public Assignment getRulesAssignment_3_0() { return cRulesAssignment_3_0; }

		//CSSRuleDefinition
		public RuleCall getRulesCSSRuleDefinitionParserRuleCall_3_0_0() { return cRulesCSSRuleDefinitionParserRuleCall_3_0_0; }

		//subpackages+=PackageDefinition
		public Assignment getSubpackagesAssignment_3_1() { return cSubpackagesAssignment_3_1; }

		//PackageDefinition
		public RuleCall getSubpackagesPackageDefinitionParserRuleCall_3_1_0() { return cSubpackagesPackageDefinitionParserRuleCall_3_1_0; }

		//elements+=ElementDeclartion
		public Assignment getElementsAssignment_3_2() { return cElementsAssignment_3_2; }

		//ElementDeclartion
		public RuleCall getElementsElementDeclartionParserRuleCall_3_2_0() { return cElementsElementDeclartionParserRuleCall_3_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class DokuElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Doku");
		private final Assignment cContentAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cContentJDOCTerminalRuleCall_0 = (RuleCall)cContentAssignment.eContents().get(0);
		
		//Doku:
		//
		//	content=JDOC;
		public ParserRule getRule() { return rule; }

		//content=JDOC
		public Assignment getContentAssignment() { return cContentAssignment; }

		//JDOC
		public RuleCall getContentJDOCTerminalRuleCall_0() { return cContentJDOCTerminalRuleCall_0; }
	}

	public class CSSBaseTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSBaseType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cINTKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cDOUBLEKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		private final Keyword cUDOUBLEKeyword_2 = (Keyword)cAlternatives.eContents().get(2);
		
		//CSSBaseType returns CSSRule:
		//
		//	"INT" | "DOUBLE" | "UDOUBLE";
		public ParserRule getRule() { return rule; }

		//"INT" | "DOUBLE" | "UDOUBLE"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"INT"
		public Keyword getINTKeyword_0() { return cINTKeyword_0; }

		//"DOUBLE"
		public Keyword getDOUBLEKeyword_1() { return cDOUBLEKeyword_1; }

		//"UDOUBLE"
		public Keyword getUDOUBLEKeyword_2() { return cUDOUBLEKeyword_2; }
	}

	public class ElementDeclartionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ElementDeclartion");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDokuAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDokuDokuParserRuleCall_0_0 = (RuleCall)cDokuAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Alternatives cAlternatives_3 = (Alternatives)cGroup.eContents().get(3);
		private final Assignment cPropertiesAssignment_3_0 = (Assignment)cAlternatives_3.eContents().get(0);
		private final RuleCall cPropertiesPropertyDefinitionParserRuleCall_3_0_0 = (RuleCall)cPropertiesAssignment_3_0.eContents().get(0);
		private final Assignment cPseudoClassesAssignment_3_1 = (Assignment)cAlternatives_3.eContents().get(1);
		private final RuleCall cPseudoClassesPseudoClassDefinitionParserRuleCall_3_1_0 = (RuleCall)cPseudoClassesAssignment_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//ElementDeclartion:
		//
		//	doku=Doku? name=QualifiedName "{" (properties+=PropertyDefinition | pseudoClasses+=PseudoClassDefinition)* "}";
		public ParserRule getRule() { return rule; }

		//doku=Doku? name=QualifiedName "{" (properties+=PropertyDefinition | pseudoClasses+=PseudoClassDefinition)* "}"
		public Group getGroup() { return cGroup; }

		//doku=Doku?
		public Assignment getDokuAssignment_0() { return cDokuAssignment_0; }

		//Doku
		public RuleCall getDokuDokuParserRuleCall_0_0() { return cDokuDokuParserRuleCall_0_0; }

		//name=QualifiedName
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_1_0() { return cNameQualifiedNameParserRuleCall_1_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//(properties+=PropertyDefinition | pseudoClasses+=PseudoClassDefinition)*
		public Alternatives getAlternatives_3() { return cAlternatives_3; }

		//properties+=PropertyDefinition
		public Assignment getPropertiesAssignment_3_0() { return cPropertiesAssignment_3_0; }

		//PropertyDefinition
		public RuleCall getPropertiesPropertyDefinitionParserRuleCall_3_0_0() { return cPropertiesPropertyDefinitionParserRuleCall_3_0_0; }

		//pseudoClasses+=PseudoClassDefinition
		public Assignment getPseudoClassesAssignment_3_1() { return cPseudoClassesAssignment_3_1; }

		//PseudoClassDefinition
		public RuleCall getPseudoClassesPseudoClassDefinitionParserRuleCall_3_1_0() { return cPseudoClassesPseudoClassDefinitionParserRuleCall_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class PropertyDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PropertyDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDokuAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDokuDokuParserRuleCall_0_0 = (RuleCall)cDokuAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Assignment cRuleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRuleCSSRuleOrParserRuleCall_2_0 = (RuleCall)cRuleAssignment_2.eContents().get(0);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cDefaultKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Assignment cDefaultAssignment_3_1 = (Assignment)cGroup_3.eContents().get(1);
		private final RuleCall cDefaultCSSDefaultValueParserRuleCall_3_1_0 = (RuleCall)cDefaultAssignment_3_1.eContents().get(0);
		private final Keyword cSemicolonKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//PropertyDefinition:
		//
		//	doku=Doku? name=ID rule=CSSRuleOr ("default:" default=CSSDefaultValue)? ";";
		public ParserRule getRule() { return rule; }

		//doku=Doku? name=ID rule=CSSRuleOr ("default:" default=CSSDefaultValue)? ";"
		public Group getGroup() { return cGroup; }

		//doku=Doku?
		public Assignment getDokuAssignment_0() { return cDokuAssignment_0; }

		//Doku
		public RuleCall getDokuDokuParserRuleCall_0_0() { return cDokuDokuParserRuleCall_0_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//rule=CSSRuleOr
		public Assignment getRuleAssignment_2() { return cRuleAssignment_2; }

		//CSSRuleOr
		public RuleCall getRuleCSSRuleOrParserRuleCall_2_0() { return cRuleCSSRuleOrParserRuleCall_2_0; }

		//("default:" default=CSSDefaultValue)?
		public Group getGroup_3() { return cGroup_3; }

		//"default:"
		public Keyword getDefaultKeyword_3_0() { return cDefaultKeyword_3_0; }

		//default=CSSDefaultValue
		public Assignment getDefaultAssignment_3_1() { return cDefaultAssignment_3_1; }

		//CSSDefaultValue
		public RuleCall getDefaultCSSDefaultValueParserRuleCall_3_1_0() { return cDefaultCSSDefaultValueParserRuleCall_3_1_0; }

		//";"
		public Keyword getSemicolonKeyword_4() { return cSemicolonKeyword_4; }
	}

	public class PseudoClassDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PseudoClassDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cDokuAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cDokuDokuParserRuleCall_0_0 = (RuleCall)cDokuAssignment_0.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNamePSEUDOTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//PseudoClassDefinition:
		//
		//	doku=Doku? name=PSEUDO;
		public ParserRule getRule() { return rule; }

		//doku=Doku? name=PSEUDO
		public Group getGroup() { return cGroup; }

		//doku=Doku?
		public Assignment getDokuAssignment_0() { return cDokuAssignment_0; }

		//Doku
		public RuleCall getDokuDokuParserRuleCall_0_0() { return cDokuDokuParserRuleCall_0_0; }

		//name=PSEUDO
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//PSEUDO
		public RuleCall getNamePSEUDOTerminalRuleCall_1_0() { return cNamePSEUDOTerminalRuleCall_1_0; }
	}

	public class CSSRuleIdElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRuleId");
		private final Assignment cNameAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cNameQualifiedNameParserRuleCall_0 = (RuleCall)cNameAssignment.eContents().get(0);
		
		//CSSRuleId:
		//
		//	name=QualifiedName;
		public ParserRule getRule() { return rule; }

		//name=QualifiedName
		public Assignment getNameAssignment() { return cNameAssignment; }

		//QualifiedName
		public RuleCall getNameQualifiedNameParserRuleCall_0() { return cNameQualifiedNameParserRuleCall_0; }
	}

	public class CSSRuleRefElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRuleRef");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLessThanSignKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cRefAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final CrossReference cRefCSSRuleIdCrossReference_1_0 = (CrossReference)cRefAssignment_1.eContents().get(0);
		private final RuleCall cRefCSSRuleIdQualifiedNameParserRuleCall_1_0_1 = (RuleCall)cRefCSSRuleIdCrossReference_1_0.eContents().get(1);
		private final Keyword cGreaterThanSignKeyword_2 = (Keyword)cGroup.eContents().get(2);
		
		//CSSRuleRef:
		//
		//	"<" ref=[CSSRuleId|QualifiedName] ">";
		public ParserRule getRule() { return rule; }

		//"<" ref=[CSSRuleId|QualifiedName] ">"
		public Group getGroup() { return cGroup; }

		//"<"
		public Keyword getLessThanSignKeyword_0() { return cLessThanSignKeyword_0; }

		//ref=[CSSRuleId|QualifiedName]
		public Assignment getRefAssignment_1() { return cRefAssignment_1; }

		//[CSSRuleId|QualifiedName]
		public CrossReference getRefCSSRuleIdCrossReference_1_0() { return cRefCSSRuleIdCrossReference_1_0; }

		//QualifiedName
		public RuleCall getRefCSSRuleIdQualifiedNameParserRuleCall_1_0_1() { return cRefCSSRuleIdQualifiedNameParserRuleCall_1_0_1; }

		//">"
		public Keyword getGreaterThanSignKeyword_2() { return cGreaterThanSignKeyword_2; }
	}

	public class CSSRuleDefinitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRuleDefinition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCSSRuleDefinitionAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cDokuAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDokuDokuParserRuleCall_1_0 = (RuleCall)cDokuAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameCSSRuleIdParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cEqualsSignKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cRAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cRCSSRuleOrParserRuleCall_4_0 = (RuleCall)cRAssignment_4.eContents().get(0);
		private final Keyword cSemicolonKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//CSSRuleDefinition:
		//
		//	{CSSRuleDefinition} doku=Doku? name=CSSRuleId "=" r=CSSRuleOr ";";
		public ParserRule getRule() { return rule; }

		//{CSSRuleDefinition} doku=Doku? name=CSSRuleId "=" r=CSSRuleOr ";"
		public Group getGroup() { return cGroup; }

		//{CSSRuleDefinition}
		public Action getCSSRuleDefinitionAction_0() { return cCSSRuleDefinitionAction_0; }

		//doku=Doku?
		public Assignment getDokuAssignment_1() { return cDokuAssignment_1; }

		//Doku
		public RuleCall getDokuDokuParserRuleCall_1_0() { return cDokuDokuParserRuleCall_1_0; }

		//name=CSSRuleId
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//CSSRuleId
		public RuleCall getNameCSSRuleIdParserRuleCall_2_0() { return cNameCSSRuleIdParserRuleCall_2_0; }

		//"="
		public Keyword getEqualsSignKeyword_3() { return cEqualsSignKeyword_3; }

		//r=CSSRuleOr
		public Assignment getRAssignment_4() { return cRAssignment_4; }

		//CSSRuleOr
		public RuleCall getRCSSRuleOrParserRuleCall_4_0() { return cRCSSRuleOrParserRuleCall_4_0; }

		//";"
		public Keyword getSemicolonKeyword_5() { return cSemicolonKeyword_5; }
	}

	public class CSSRuleOrElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRuleOr");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cCSSRuleXorParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cCSSRuleOrOrsAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cVerticalLineKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cOrsAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cOrsCSSRuleXorParserRuleCall_1_1_1_0 = (RuleCall)cOrsAssignment_1_1_1.eContents().get(0);
		
		//CSSRuleOr returns CSSRule:
		//
		//	CSSRuleXor ({CSSRuleOr.ors+=current} ("|" ors+=CSSRuleXor)+)?;
		public ParserRule getRule() { return rule; }

		//CSSRuleXor ({CSSRuleOr.ors+=current} ("|" ors+=CSSRuleXor)+)?
		public Group getGroup() { return cGroup; }

		//CSSRuleXor
		public RuleCall getCSSRuleXorParserRuleCall_0() { return cCSSRuleXorParserRuleCall_0; }

		//({CSSRuleOr.ors+=current} ("|" ors+=CSSRuleXor)+)?
		public Group getGroup_1() { return cGroup_1; }

		//{CSSRuleOr.ors+=current}
		public Action getCSSRuleOrOrsAction_1_0() { return cCSSRuleOrOrsAction_1_0; }

		//("|" ors+=CSSRuleXor)+
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"|"
		public Keyword getVerticalLineKeyword_1_1_0() { return cVerticalLineKeyword_1_1_0; }

		//ors+=CSSRuleXor
		public Assignment getOrsAssignment_1_1_1() { return cOrsAssignment_1_1_1; }

		//CSSRuleXor
		public RuleCall getOrsCSSRuleXorParserRuleCall_1_1_1_0() { return cOrsCSSRuleXorParserRuleCall_1_1_1_0; }
	}

	public class CSSRuleXorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRuleXor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cCSSRuleConcatParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cCSSRuleXorXorsAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Group cGroup_1_1 = (Group)cGroup_1.eContents().get(1);
		private final Keyword cVerticalLineVerticalLineKeyword_1_1_0 = (Keyword)cGroup_1_1.eContents().get(0);
		private final Assignment cXorsAssignment_1_1_1 = (Assignment)cGroup_1_1.eContents().get(1);
		private final RuleCall cXorsCSSRuleConcatParserRuleCall_1_1_1_0 = (RuleCall)cXorsAssignment_1_1_1.eContents().get(0);
		
		//CSSRuleXor returns CSSRule:
		//
		//	CSSRuleConcat ({CSSRuleXor.xors+=current} ("||" xors+=CSSRuleConcat)+)?;
		public ParserRule getRule() { return rule; }

		//CSSRuleConcat ({CSSRuleXor.xors+=current} ("||" xors+=CSSRuleConcat)+)?
		public Group getGroup() { return cGroup; }

		//CSSRuleConcat
		public RuleCall getCSSRuleConcatParserRuleCall_0() { return cCSSRuleConcatParserRuleCall_0; }

		//({CSSRuleXor.xors+=current} ("||" xors+=CSSRuleConcat)+)?
		public Group getGroup_1() { return cGroup_1; }

		//{CSSRuleXor.xors+=current}
		public Action getCSSRuleXorXorsAction_1_0() { return cCSSRuleXorXorsAction_1_0; }

		//("||" xors+=CSSRuleConcat)+
		public Group getGroup_1_1() { return cGroup_1_1; }

		//"||"
		public Keyword getVerticalLineVerticalLineKeyword_1_1_0() { return cVerticalLineVerticalLineKeyword_1_1_0; }

		//xors+=CSSRuleConcat
		public Assignment getXorsAssignment_1_1_1() { return cXorsAssignment_1_1_1; }

		//CSSRuleConcat
		public RuleCall getXorsCSSRuleConcatParserRuleCall_1_1_1_0() { return cXorsCSSRuleConcatParserRuleCall_1_1_1_0; }
	}

	public class CSSRuleConcatElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRuleConcat");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cCSSRulePostfixParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cCSSRuleConcatConcAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cConcAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cConcCSSRulePostfixParserRuleCall_1_1_0 = (RuleCall)cConcAssignment_1_1.eContents().get(0);
		
		//CSSRuleConcat returns CSSRule:
		//
		//	CSSRulePostfix ({CSSRuleConcat.conc+=current} conc+=CSSRulePostfix+)?;
		public ParserRule getRule() { return rule; }

		//CSSRulePostfix ({CSSRuleConcat.conc+=current} conc+=CSSRulePostfix+)?
		public Group getGroup() { return cGroup; }

		//CSSRulePostfix
		public RuleCall getCSSRulePostfixParserRuleCall_0() { return cCSSRulePostfixParserRuleCall_0; }

		//({CSSRuleConcat.conc+=current} conc+=CSSRulePostfix+)?
		public Group getGroup_1() { return cGroup_1; }

		//{CSSRuleConcat.conc+=current}
		public Action getCSSRuleConcatConcAction_1_0() { return cCSSRuleConcatConcAction_1_0; }

		//conc+=CSSRulePostfix+
		public Assignment getConcAssignment_1_1() { return cConcAssignment_1_1; }

		//CSSRulePostfix
		public RuleCall getConcCSSRulePostfixParserRuleCall_1_1_0() { return cConcCSSRulePostfixParserRuleCall_1_1_0; }
	}

	public class CSSRulePostfixElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRulePostfix");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final RuleCall cCSSRulePrimaryParserRuleCall_0 = (RuleCall)cGroup.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final Action cCSSRulePostfixRuleAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final Assignment cCardinalityAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final Alternatives cCardinalityAlternatives_1_1_0 = (Alternatives)cCardinalityAssignment_1_1.eContents().get(0);
		private final Keyword cCardinalityAsteriskKeyword_1_1_0_0 = (Keyword)cCardinalityAlternatives_1_1_0.eContents().get(0);
		private final Keyword cCardinalityPlusSignKeyword_1_1_0_1 = (Keyword)cCardinalityAlternatives_1_1_0.eContents().get(1);
		private final Keyword cCardinalityQuestionMarkKeyword_1_1_0_2 = (Keyword)cCardinalityAlternatives_1_1_0.eContents().get(2);
		
		//CSSRulePostfix returns CSSRule:
		//
		//	CSSRulePrimary ({CSSRulePostfix.rule=current} cardinality=("*" | "+" | "?"))?;
		public ParserRule getRule() { return rule; }

		//CSSRulePrimary ({CSSRulePostfix.rule=current} cardinality=("*" | "+" | "?"))?
		public Group getGroup() { return cGroup; }

		//CSSRulePrimary
		public RuleCall getCSSRulePrimaryParserRuleCall_0() { return cCSSRulePrimaryParserRuleCall_0; }

		//({CSSRulePostfix.rule=current} cardinality=("*" | "+" | "?"))?
		public Group getGroup_1() { return cGroup_1; }

		//{CSSRulePostfix.rule=current}
		public Action getCSSRulePostfixRuleAction_1_0() { return cCSSRulePostfixRuleAction_1_0; }

		//cardinality=("*" | "+" | "?")
		public Assignment getCardinalityAssignment_1_1() { return cCardinalityAssignment_1_1; }

		//"*" | "+" | "?"
		public Alternatives getCardinalityAlternatives_1_1_0() { return cCardinalityAlternatives_1_1_0; }

		//"*"
		public Keyword getCardinalityAsteriskKeyword_1_1_0_0() { return cCardinalityAsteriskKeyword_1_1_0_0; }

		//"+"
		public Keyword getCardinalityPlusSignKeyword_1_1_0_1() { return cCardinalityPlusSignKeyword_1_1_0_1; }

		//"?"
		public Keyword getCardinalityQuestionMarkKeyword_1_1_0_2() { return cCardinalityQuestionMarkKeyword_1_1_0_2; }
	}

	public class CSSRuleBracketElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRuleBracket");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cCSSRuleBracketAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cLeftSquareBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cInnerAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cInnerCSSRuleOrParserRuleCall_2_0 = (RuleCall)cInnerAssignment_2.eContents().get(0);
		private final Keyword cRightSquareBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//CSSRuleBracket returns CSSRule:
		//
		//	{CSSRuleBracket} "[" inner=CSSRuleOr "]";
		public ParserRule getRule() { return rule; }

		//{CSSRuleBracket} "[" inner=CSSRuleOr "]"
		public Group getGroup() { return cGroup; }

		//{CSSRuleBracket}
		public Action getCSSRuleBracketAction_0() { return cCSSRuleBracketAction_0; }

		//"["
		public Keyword getLeftSquareBracketKeyword_1() { return cLeftSquareBracketKeyword_1; }

		//inner=CSSRuleOr
		public Assignment getInnerAssignment_2() { return cInnerAssignment_2; }

		//CSSRuleOr
		public RuleCall getInnerCSSRuleOrParserRuleCall_2_0() { return cInnerCSSRuleOrParserRuleCall_2_0; }

		//"]"
		public Keyword getRightSquareBracketKeyword_3() { return cRightSquareBracketKeyword_3; }
	}

	public class CSSRulePrimaryElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRulePrimary");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCSSRuleRefParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCSSRuleBracketParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCSSRuleLiteralParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cCSSBaseTypeParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//CSSRulePrimary returns CSSRule:
		//
		//	CSSRuleRef | CSSRuleBracket | CSSRuleLiteral | CSSBaseType;
		public ParserRule getRule() { return rule; }

		//CSSRuleRef | CSSRuleBracket | CSSRuleLiteral | CSSBaseType
		public Alternatives getAlternatives() { return cAlternatives; }

		//CSSRuleRef
		public RuleCall getCSSRuleRefParserRuleCall_0() { return cCSSRuleRefParserRuleCall_0; }

		//CSSRuleBracket
		public RuleCall getCSSRuleBracketParserRuleCall_1() { return cCSSRuleBracketParserRuleCall_1; }

		//CSSRuleLiteral
		public RuleCall getCSSRuleLiteralParserRuleCall_2() { return cCSSRuleLiteralParserRuleCall_2; }

		//CSSBaseType
		public RuleCall getCSSBaseTypeParserRuleCall_3() { return cCSSBaseTypeParserRuleCall_3; }
	}

	public class CSSRuleLiteralElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSRuleLiteral");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cCSSRuleLiteralAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cValueAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final RuleCall cValueIDTerminalRuleCall_0_1_0 = (RuleCall)cValueAssignment_0_1.eContents().get(0);
		private final Assignment cValueAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cValueCommaKeyword_1_0 = (Keyword)cValueAssignment_1.eContents().get(0);
		
		//CSSRuleLiteral returns CSSRule:
		//
		//	{CSSRuleLiteral} value=ID | value=",";
		public ParserRule getRule() { return rule; }

		//{CSSRuleLiteral} value=ID | value=","
		public Alternatives getAlternatives() { return cAlternatives; }

		//{CSSRuleLiteral} value=ID
		public Group getGroup_0() { return cGroup_0; }

		//{CSSRuleLiteral}
		public Action getCSSRuleLiteralAction_0_0() { return cCSSRuleLiteralAction_0_0; }

		//value=ID
		public Assignment getValueAssignment_0_1() { return cValueAssignment_0_1; }

		//ID
		public RuleCall getValueIDTerminalRuleCall_0_1_0() { return cValueIDTerminalRuleCall_0_1_0; }

		//value=","
		public Assignment getValueAssignment_1() { return cValueAssignment_1; }

		//","
		public Keyword getValueCommaKeyword_1_0() { return cValueCommaKeyword_1_0; }
	}

	public class CSSDefaultValueElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CSSDefaultValue");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCSSRuleLiteralParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final RuleCall cINTTerminalRuleCall_2_0 = (RuleCall)cGroup_2.eContents().get(0);
		private final Keyword cFullStopKeyword_2_1 = (Keyword)cGroup_2.eContents().get(1);
		private final RuleCall cINTTerminalRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		private final RuleCall cSTRINGTerminalRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//CSSDefaultValue:
		//
		//	CSSRuleLiteral | INT | INT* "." INT+ | STRING;
		public ParserRule getRule() { return rule; }

		//CSSRuleLiteral | INT | INT* "." INT+ | STRING
		public Alternatives getAlternatives() { return cAlternatives; }

		//CSSRuleLiteral
		public RuleCall getCSSRuleLiteralParserRuleCall_0() { return cCSSRuleLiteralParserRuleCall_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }

		//INT* "." INT+
		public Group getGroup_2() { return cGroup_2; }

		//INT*
		public RuleCall getINTTerminalRuleCall_2_0() { return cINTTerminalRuleCall_2_0; }

		//"."
		public Keyword getFullStopKeyword_2_1() { return cFullStopKeyword_2_1; }

		//INT+
		public RuleCall getINTTerminalRuleCall_2_2() { return cINTTerminalRuleCall_2_2; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_3() { return cSTRINGTerminalRuleCall_3; }
	}
	
	
	private CssExtensionElements pCssExtension;
	private TerminalRule tPSEUDO;
	private TerminalRule tID;
	private TerminalRule tJDOC;
	private TerminalRule tML_COMMENT;
	private TerminalRule tSL_COMMENT;
	private ImportElements pImport;
	private ValidIDElements pValidID;
	private QualifiedNameElements pQualifiedName;
	private QualifiedNameWithWildCardElements pQualifiedNameWithWildCard;
	private PackageDefinitionElements pPackageDefinition;
	private DokuElements pDoku;
	private CSSBaseTypeElements pCSSBaseType;
	private ElementDeclartionElements pElementDeclartion;
	private PropertyDefinitionElements pPropertyDefinition;
	private PseudoClassDefinitionElements pPseudoClassDefinition;
	private CSSRuleIdElements pCSSRuleId;
	private CSSRuleRefElements pCSSRuleRef;
	private CSSRuleDefinitionElements pCSSRuleDefinition;
	private CSSRuleOrElements pCSSRuleOr;
	private CSSRuleXorElements pCSSRuleXor;
	private CSSRuleConcatElements pCSSRuleConcat;
	private CSSRulePostfixElements pCSSRulePostfix;
	private CSSRuleBracketElements pCSSRuleBracket;
	private CSSRulePrimaryElements pCSSRulePrimary;
	private CSSRuleLiteralElements pCSSRuleLiteral;
	private CSSDefaultValueElements pCSSDefaultValue;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public CssExtDslGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("at.bestsolution.efxclipse.tooling.css.cssext.CssExtDsl".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////	packageDef=PackageDefinition?
	// //	rule=CSSRuleSet
	// CssExtension:
	//
	//	imports+=Import* packageDef=PackageDefinition?;
	public CssExtensionElements getCssExtensionAccess() {
		return (pCssExtension != null) ? pCssExtension : (pCssExtension = new CssExtensionElements());
	}
	
	public ParserRule getCssExtensionRule() {
		return getCssExtensionAccess().getRule();
	}

	//terminal PSEUDO:
	//
	//	":" !" " ID;
	public TerminalRule getPSEUDORule() {
		return (tPSEUDO != null) ? tPSEUDO : (tPSEUDO = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "PSEUDO"));
	} 

	//terminal ID:
	//
	//	("a".."z" | "A".."Z" | "_" | "-") ("a".."z" | "A".."Z" | "_" | "0".."9" | "-")*;
	public TerminalRule getIDRule() {
		return (tID != null) ? tID : (tID = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ID"));
	} 

	//terminal JDOC:
	//
	//	"/ **"->"* /";
	public TerminalRule getJDOCRule() {
		return (tJDOC != null) ? tJDOC : (tJDOC = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "JDOC"));
	} 

	//terminal ML_COMMENT:
	//
	//	"/ *" !"*"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return (tML_COMMENT != null) ? tML_COMMENT : (tML_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ML_COMMENT"));
	} 

	//terminal SL_COMMENT:
	//
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return (tSL_COMMENT != null) ? tSL_COMMENT : (tSL_COMMENT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SL_COMMENT"));
	} 

	//Import:
	//
	//	"import" importedNamespace=QualifiedNameWithWildCard;
	public ImportElements getImportAccess() {
		return (pImport != null) ? pImport : (pImport = new ImportElements());
	}
	
	public ParserRule getImportRule() {
		return getImportAccess().getRule();
	}

	//ValidID:
	//
	//	ID;
	public ValidIDElements getValidIDAccess() {
		return (pValidID != null) ? pValidID : (pValidID = new ValidIDElements());
	}
	
	public ParserRule getValidIDRule() {
		return getValidIDAccess().getRule();
	}

	//QualifiedName:
	//
	//	ValidID ("." ValidID)*;
	public QualifiedNameElements getQualifiedNameAccess() {
		return (pQualifiedName != null) ? pQualifiedName : (pQualifiedName = new QualifiedNameElements());
	}
	
	public ParserRule getQualifiedNameRule() {
		return getQualifiedNameAccess().getRule();
	}

	//QualifiedNameWithWildCard:
	//
	//	QualifiedName ("." "*")?;
	public QualifiedNameWithWildCardElements getQualifiedNameWithWildCardAccess() {
		return (pQualifiedNameWithWildCard != null) ? pQualifiedNameWithWildCard : (pQualifiedNameWithWildCard = new QualifiedNameWithWildCardElements());
	}
	
	public ParserRule getQualifiedNameWithWildCardRule() {
		return getQualifiedNameWithWildCardAccess().getRule();
	}

	//PackageDefinition:
	//
	//	"package" name=QualifiedName "{" (rules+=CSSRuleDefinition | subpackages+=PackageDefinition |
	//
	//	elements+=ElementDeclartion)* "}";
	public PackageDefinitionElements getPackageDefinitionAccess() {
		return (pPackageDefinition != null) ? pPackageDefinition : (pPackageDefinition = new PackageDefinitionElements());
	}
	
	public ParserRule getPackageDefinitionRule() {
		return getPackageDefinitionAccess().getRule();
	}

	//Doku:
	//
	//	content=JDOC;
	public DokuElements getDokuAccess() {
		return (pDoku != null) ? pDoku : (pDoku = new DokuElements());
	}
	
	public ParserRule getDokuRule() {
		return getDokuAccess().getRule();
	}

	//CSSBaseType returns CSSRule:
	//
	//	"INT" | "DOUBLE" | "UDOUBLE";
	public CSSBaseTypeElements getCSSBaseTypeAccess() {
		return (pCSSBaseType != null) ? pCSSBaseType : (pCSSBaseType = new CSSBaseTypeElements());
	}
	
	public ParserRule getCSSBaseTypeRule() {
		return getCSSBaseTypeAccess().getRule();
	}

	//ElementDeclartion:
	//
	//	doku=Doku? name=QualifiedName "{" (properties+=PropertyDefinition | pseudoClasses+=PseudoClassDefinition)* "}";
	public ElementDeclartionElements getElementDeclartionAccess() {
		return (pElementDeclartion != null) ? pElementDeclartion : (pElementDeclartion = new ElementDeclartionElements());
	}
	
	public ParserRule getElementDeclartionRule() {
		return getElementDeclartionAccess().getRule();
	}

	//PropertyDefinition:
	//
	//	doku=Doku? name=ID rule=CSSRuleOr ("default:" default=CSSDefaultValue)? ";";
	public PropertyDefinitionElements getPropertyDefinitionAccess() {
		return (pPropertyDefinition != null) ? pPropertyDefinition : (pPropertyDefinition = new PropertyDefinitionElements());
	}
	
	public ParserRule getPropertyDefinitionRule() {
		return getPropertyDefinitionAccess().getRule();
	}

	//PseudoClassDefinition:
	//
	//	doku=Doku? name=PSEUDO;
	public PseudoClassDefinitionElements getPseudoClassDefinitionAccess() {
		return (pPseudoClassDefinition != null) ? pPseudoClassDefinition : (pPseudoClassDefinition = new PseudoClassDefinitionElements());
	}
	
	public ParserRule getPseudoClassDefinitionRule() {
		return getPseudoClassDefinitionAccess().getRule();
	}

	//CSSRuleId:
	//
	//	name=QualifiedName;
	public CSSRuleIdElements getCSSRuleIdAccess() {
		return (pCSSRuleId != null) ? pCSSRuleId : (pCSSRuleId = new CSSRuleIdElements());
	}
	
	public ParserRule getCSSRuleIdRule() {
		return getCSSRuleIdAccess().getRule();
	}

	//CSSRuleRef:
	//
	//	"<" ref=[CSSRuleId|QualifiedName] ">";
	public CSSRuleRefElements getCSSRuleRefAccess() {
		return (pCSSRuleRef != null) ? pCSSRuleRef : (pCSSRuleRef = new CSSRuleRefElements());
	}
	
	public ParserRule getCSSRuleRefRule() {
		return getCSSRuleRefAccess().getRule();
	}

	//CSSRuleDefinition:
	//
	//	{CSSRuleDefinition} doku=Doku? name=CSSRuleId "=" r=CSSRuleOr ";";
	public CSSRuleDefinitionElements getCSSRuleDefinitionAccess() {
		return (pCSSRuleDefinition != null) ? pCSSRuleDefinition : (pCSSRuleDefinition = new CSSRuleDefinitionElements());
	}
	
	public ParserRule getCSSRuleDefinitionRule() {
		return getCSSRuleDefinitionAccess().getRule();
	}

	//CSSRuleOr returns CSSRule:
	//
	//	CSSRuleXor ({CSSRuleOr.ors+=current} ("|" ors+=CSSRuleXor)+)?;
	public CSSRuleOrElements getCSSRuleOrAccess() {
		return (pCSSRuleOr != null) ? pCSSRuleOr : (pCSSRuleOr = new CSSRuleOrElements());
	}
	
	public ParserRule getCSSRuleOrRule() {
		return getCSSRuleOrAccess().getRule();
	}

	//CSSRuleXor returns CSSRule:
	//
	//	CSSRuleConcat ({CSSRuleXor.xors+=current} ("||" xors+=CSSRuleConcat)+)?;
	public CSSRuleXorElements getCSSRuleXorAccess() {
		return (pCSSRuleXor != null) ? pCSSRuleXor : (pCSSRuleXor = new CSSRuleXorElements());
	}
	
	public ParserRule getCSSRuleXorRule() {
		return getCSSRuleXorAccess().getRule();
	}

	//CSSRuleConcat returns CSSRule:
	//
	//	CSSRulePostfix ({CSSRuleConcat.conc+=current} conc+=CSSRulePostfix+)?;
	public CSSRuleConcatElements getCSSRuleConcatAccess() {
		return (pCSSRuleConcat != null) ? pCSSRuleConcat : (pCSSRuleConcat = new CSSRuleConcatElements());
	}
	
	public ParserRule getCSSRuleConcatRule() {
		return getCSSRuleConcatAccess().getRule();
	}

	//CSSRulePostfix returns CSSRule:
	//
	//	CSSRulePrimary ({CSSRulePostfix.rule=current} cardinality=("*" | "+" | "?"))?;
	public CSSRulePostfixElements getCSSRulePostfixAccess() {
		return (pCSSRulePostfix != null) ? pCSSRulePostfix : (pCSSRulePostfix = new CSSRulePostfixElements());
	}
	
	public ParserRule getCSSRulePostfixRule() {
		return getCSSRulePostfixAccess().getRule();
	}

	//CSSRuleBracket returns CSSRule:
	//
	//	{CSSRuleBracket} "[" inner=CSSRuleOr "]";
	public CSSRuleBracketElements getCSSRuleBracketAccess() {
		return (pCSSRuleBracket != null) ? pCSSRuleBracket : (pCSSRuleBracket = new CSSRuleBracketElements());
	}
	
	public ParserRule getCSSRuleBracketRule() {
		return getCSSRuleBracketAccess().getRule();
	}

	//CSSRulePrimary returns CSSRule:
	//
	//	CSSRuleRef | CSSRuleBracket | CSSRuleLiteral | CSSBaseType;
	public CSSRulePrimaryElements getCSSRulePrimaryAccess() {
		return (pCSSRulePrimary != null) ? pCSSRulePrimary : (pCSSRulePrimary = new CSSRulePrimaryElements());
	}
	
	public ParserRule getCSSRulePrimaryRule() {
		return getCSSRulePrimaryAccess().getRule();
	}

	//CSSRuleLiteral returns CSSRule:
	//
	//	{CSSRuleLiteral} value=ID | value=",";
	public CSSRuleLiteralElements getCSSRuleLiteralAccess() {
		return (pCSSRuleLiteral != null) ? pCSSRuleLiteral : (pCSSRuleLiteral = new CSSRuleLiteralElements());
	}
	
	public ParserRule getCSSRuleLiteralRule() {
		return getCSSRuleLiteralAccess().getRule();
	}

	//CSSDefaultValue:
	//
	//	CSSRuleLiteral | INT | INT* "." INT+ | STRING;
	public CSSDefaultValueElements getCSSDefaultValueAccess() {
		return (pCSSDefaultValue != null) ? pCSSDefaultValue : (pCSSDefaultValue = new CSSDefaultValueElements());
	}
	
	public ParserRule getCSSDefaultValueRule() {
		return getCSSDefaultValueAccess().getRule();
	}

	//terminal INT returns ecore::EInt:
	//
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal WS:
	//
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
