/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.css.cssext.ui.contentassist;

import at.bestsolution.efxclipse.tooling.css.cssext.ui.contentassist.AbstractCssExtDslProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class CssExtDslProposalProvider extends AbstractCssExtDslProposalProvider {

}
