/*
 * generated by Xtext
 */
package at.bestsolution.efxclipse.tooling.css.cssext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class CssExtDslUiModule extends at.bestsolution.efxclipse.tooling.css.cssext.ui.AbstractCssExtDslUiModule {
	public CssExtDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
