/*
* generated by Xtext
*/
package at.bestsolution.efxclipse.tooling.css.cssext;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class CssExtDslUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return at.bestsolution.efxclipse.tooling.css.cssext.ui.internal.CssExtDslActivator.getInstance().getInjector("at.bestsolution.efxclipse.tooling.css.cssext.CssExtDsl");
	}
	
}
